# -*- coding: utf-8 -*-
"""p29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SetsHqjayUNOy5fwn5rdbRTAGjOVpyj6
"""

a_start = 2
a_end = 100
b_start = 2
b_end = 100

squares = set([])
for a in range(a_start,a_end+1):
    for b in range(b_start,b_end+1):
        squares.add(a**b)

print(squares)

len(squares)